/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FoqueSlammersIndexImport } from './routes/foque-slammers/index'
import { Route as FoqueSlammersGameIndexImport } from './routes/foque-slammers/game/index'

// Create/Update Routes

const FoqueSlammersIndexRoute = FoqueSlammersIndexImport.update({
  id: '/foque-slammers/',
  path: '/foque-slammers/',
  getParentRoute: () => rootRoute,
} as any)

const FoqueSlammersGameIndexRoute = FoqueSlammersGameIndexImport.update({
  id: '/foque-slammers/game/',
  path: '/foque-slammers/game/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/foque-slammers/': {
      id: '/foque-slammers/'
      path: '/foque-slammers'
      fullPath: '/foque-slammers'
      preLoaderRoute: typeof FoqueSlammersIndexImport
      parentRoute: typeof rootRoute
    }
    '/foque-slammers/game/': {
      id: '/foque-slammers/game/'
      path: '/foque-slammers/game'
      fullPath: '/foque-slammers/game'
      preLoaderRoute: typeof FoqueSlammersGameIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/foque-slammers': typeof FoqueSlammersIndexRoute
  '/foque-slammers/game': typeof FoqueSlammersGameIndexRoute
}

export interface FileRoutesByTo {
  '/foque-slammers': typeof FoqueSlammersIndexRoute
  '/foque-slammers/game': typeof FoqueSlammersGameIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/foque-slammers/': typeof FoqueSlammersIndexRoute
  '/foque-slammers/game/': typeof FoqueSlammersGameIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/foque-slammers' | '/foque-slammers/game'
  fileRoutesByTo: FileRoutesByTo
  to: '/foque-slammers' | '/foque-slammers/game'
  id: '__root__' | '/foque-slammers/' | '/foque-slammers/game/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  FoqueSlammersIndexRoute: typeof FoqueSlammersIndexRoute
  FoqueSlammersGameIndexRoute: typeof FoqueSlammersGameIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  FoqueSlammersIndexRoute: FoqueSlammersIndexRoute,
  FoqueSlammersGameIndexRoute: FoqueSlammersGameIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/foque-slammers/",
        "/foque-slammers/game/"
      ]
    },
    "/foque-slammers/": {
      "filePath": "foque-slammers/index.tsx"
    },
    "/foque-slammers/game/": {
      "filePath": "foque-slammers/game/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
